# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='字数不超过200字', max_length=200, verbose_name='文章标题')),
                ('second_title', models.CharField(help_text='字数200字以下', max_length=200, verbose_name='文章副标题')),
                ('author', models.CharField(help_text='中英文都可以', max_length=50, verbose_name='作者')),
                ('icon', models.ImageField(upload_to='', verbose_name='文章相关图片')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='轮播图片名称')),
                ('banner_img', models.ImageField(upload_to='', verbose_name='图片')),
                ('seq', models.SmallIntegerField(verbose_name='图片标识')),
            ],
            options={
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='板块名称')),
                ('sum_aticle', models.IntegerField(default=0, verbose_name='该板块文章数量')),
            ],
            options={
                'verbose_name_plural': '区块',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yafish.Plate', verbose_name='文章所属板块'),
        ),
    ]
