# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import redactor.fields
import yafish.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='字数不超过200字', max_length=200, verbose_name='文章标题')),
                ('second_title', models.CharField(blank=True, help_text='字数200字以下', max_length=200, null=True, verbose_name='文章副标题')),
                ('author', models.CharField(help_text='中英文都可以', max_length=50, verbose_name='作者')),
                ('icon', models.ImageField(blank=True, default='admin/img', storage=yafish.models.BannerStorage(), upload_to='banner_imgs/', verbose_name='文章相关图片')),
                ('content', redactor.fields.RedactorField(verbose_name='文章内容')),
                ('read_times', models.IntegerField(default=0, verbose_name='阅读数')),
                ('good_click', models.IntegerField(default=0, verbose_name='点赞次数')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='轮播图片名称')),
                ('banner_img', models.ImageField(storage=yafish.models.BannerStorage(), upload_to='banner_imgs/', verbose_name='图片')),
                ('seq', models.SmallIntegerField(verbose_name='图片标识')),
            ],
            options={
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.CreateModel(
            name='Commends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(verbose_name='用户评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yafish.Article', verbose_name='所评论的文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='板块名称')),
                ('sum_aticle', models.IntegerField(default=0, verbose_name='该板块文章数量')),
            ],
            options={
                'verbose_name_plural': '区块',
            },
        ),
        migrations.CreateModel(
            name='RecommendUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接中文名')),
                ('url', models.CharField(max_length=200, verbose_name='链接地址')),
            ],
            options={
                'verbose_name_plural': '推荐链接',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yafish.Plate', verbose_name='文章所属板块'),
        ),
    ]
