# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yafish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(storage='./', upload_to='/banner_imgs', verbose_name='图片'),
        ),
    ]
