# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import yafish.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yafish', '0002_auto_20170426_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(verbose_name='用户评论内容')),
            ],
            options={
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='RecommendUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接中文名')),
                ('url', models.CharField(max_length=200, verbose_name='链接地址')),
            ],
            options={
                'verbose_name_plural': '推荐链接',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='good_click',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_times',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(storage=yafish.models.BannerStorage(), upload_to='banner_imgs/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='commends',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yafish.Article', verbose_name='所评论的文章'),
        ),
        migrations.AddField(
            model_name='commends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
