# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yafish', '0003_auto_20170517_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='文章相关图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_title',
            field=models.CharField(blank=True, help_text='字数200字以下', max_length=200, null=True, verbose_name='文章副标题'),
        ),
    ]
